sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

cache:
  - composer
  - $HOME/.composer/cache
  directories:
    - $HOME/opt

env:
  global:
    - PATH="$TRAVIS_BUILD_DIR/vendor/bin:$PATH"
    - WP_CLI_BIN_DIR="$TRAVIS_BUILD_DIR/vendor/bin"

matrix:
  include:
    - php: 7.0
      env: WP_VERSION=latest

before_install:
  - phpenv config-rm xdebug.ini
  - if [[ $TRAVIS_PHP_VERSION = '7.0' ]]; then ./bin/install-imagick.sh; fi
  - php -m

install:
  - composer require wp-cli/wp-cli:dev-master
  - composer install
  - bash bin/install-package-tests.sh

before_script:
  - composer validate

script:
  - ./bin/test.sh
