sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

cache:
  - composer
  - $HOME/.composer/cache

env:
  global:
    - PATH="$TRAVIS_BUILD_DIR/vendor/bin:$PATH"
    - WP_CLI_BIN_DIR="$TRAVIS_BUILD_DIR/vendor/bin"

matrix:
  include:
    - php: 7.1
      env: WP_VERSION=latest
    - php: 7.0.14
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=trunk
    - php: 5.3
      env: WP_VERSION=latest

before_install:
  - phpenv config-rm xdebug.ini
  - if [[ $TRAVIS_PHP_VERSION = '5.6' || $TRAVIS_PHP_VERSION = '7.0.14' ]]; then printf "\n" | pecl install imagick; fi
  - php -m

install:
  - composer require wp-cli/wp-cli:dev-master
  - composer install
  - bash bin/install-package-tests.sh

before_script:
  - composer validate

script:
  - ./bin/test.sh
